In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from long_merge import merge_region_sheets, add_year_month
import seaborn as sns
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

In [8]:
import os
os.getcwd()

base = os.getcwd()
print(base)
print(os.listdir(base))
#현재 작업 브랜치 어디에서 작업하고 있는지 위치 확인한다.

c:\Users\heclo\KDT_RE_5th_Project\01_DataAnalysis\_artifacts
['data_visu.ipynb', 'long_format_DF(sample).ipynb', 'long_merge.py', 'preprocess_outputs', 'schema.md', '__pycache__']

In [15]:
#풍속

wind_path = "./preprocess_outputs/New_강원도_월별풍속.xlsx"

wind_sheets = pd.read_excel(wind_path, sheet_name=None)

wind_df = merge_region_sheets(wind_sheets)
wind_df = add_year_month(
        wind_df,
        drop_cols=["지점명"],
        )

wind_df.columns

Index(['지점번호', '일시', '평균풍속(m/s)', '최대풍속(m/s)', '최대풍속풍향(deg)', '최대순간풍속(m/s)',
       '최대순간풍속풍향(deg)', '구역', '연도', '월'],
      dtype='object')

In [9]:
wind_df[wind_df["구역"] == "강원도(태백)"]

,지점번호,일시,평균풍속(m/s),최대풍속(m/s),최대풍속풍향(deg),최대순간풍속(m/s),최대순간풍속풍향(deg),구역,연도,월
864,216,2020-01-01,1.2,5.6,340,12.8,340,강원도(태백),2020,1
865,216,2020-02-01,1.2,5.7,230,13.7,270,강원도(태백),2020,2
866,216,2020-03-01,1.6,7.9,250,19.2,230,강원도(태백),2020,3
867,216,2020-04-01,1.7,7.4,230,16.5,250,강원도(태백),2020,4
868,216,2020-05-01,1.6,7.6,70,13.4,320,강원도(태백),2020,5
...,...,...,...,...,...,...,...,...,...,...
931,216,2025-08-01,1.4,5.2,50,11.0,250,강원도(태백),2025,8
932,216,2025-09-01,1.3,5.4,20,11.3,70,강원도(태백),2025,9
933,216,2025-10-01,1.2,5.3,340,10.7,250,강원도(태백),2025,10
934,216,2025-11-01,1.4,6.2,200,13.9,230,강원도(태백),2025,11
935,216,2025-12-01,1.4,4.8,20,12.6,20,강원도(태백),2025,12

In [17]:
#기온

temp_path = "./preprocess_outputs/New_강원도_월별기온.xlsx"

temp_sheets = pd.read_excel(temp_path, sheet_name=None)

temp_df = merge_region_sheets(temp_sheets)
temp_df = add_year_month(
        temp_df,
        drop_cols=["지점명"],
        )

print(temp_df.columns)

temp_df[temp_df["연도"] == 2025]

Index(['지점번호', '일시', '평균기온(℃)', '평균최고기온(℃)', '최고기온(℃)', '평균최저기온(℃)', '최저기온(℃)',
       '구역', '연도', '월'],
      dtype='object')

,지점번호,일시,평균기온(℃),평균최고기온(℃),최고기온(℃),평균최저기온(℃),최저기온(℃),구역,연도,월
60,105,2025-01-01,1.9,6.1,11.7,-1.5,-9.6,강원도(강릉),2025,1
61,105,2025-02-01,1.8,6.5,17.5,-2.3,-10.4,강원도(강릉),2025,2
62,105,2025-03-01,8.0,12.7,25.2,3.8,-3.2,강원도(강릉),2025,3
63,105,2025-04-01,13.9,19.6,29.5,8.4,3.3,강원도(강릉),2025,4
64,105,2025-05-01,18.3,23.1,32.1,14.0,7.1,강원도(강릉),2025,5
...,...,...,...,...,...,...,...,...,...,...
1003,212,2025-08-01,26.5,31.8,35.4,22.9,19.7,강원도(홍천),2025,8
1004,212,2025-09-01,21.4,26.9,32.5,17.6,12.5,강원도(홍천),2025,9
1005,212,2025-10-01,14.9,20.0,26.7,11.2,-1.3,강원도(홍천),2025,10
1006,212,2025-11-01,5.9,13.2,19.0,0.4,-5.9,강원도(홍천),2025,11
1007,212,2025-12-01,12.1,18.5,11.7,6.9,-12.2,강원도(홍천),2025,12

In [18]:
#일조일사

sun_path = "./preprocess_outputs/New_강원도_월별일조일사.xlsx"

sun_sheets = pd.read_excel(sun_path, sheet_name=None)

sun_df = merge_region_sheets(sun_sheets)
sun_df = add_year_month(
        sun_df,
        drop_cols=["지점명"],
        )

sun_df.columns

Index(['지점번호', '일시', '일조합(hr)', '일조율(%)', '구역', '연도', '월'], dtype='object')

In [19]:
#강수량
rain_path = "./preprocess_outputs/New_강원도_월별강수량.xlsx"

rain_sheets = pd.read_excel(rain_path, sheet_name=None)

rain_df = merge_region_sheets(rain_sheets)
rain_df = add_year_month(
        rain_df,
        drop_cols=["지점명"],
        )


print(rain_df.columns)
rain_df[rain_df["구역"] == "강원도(강릉)"]
#필터링이 작동하는지 실행.

Index(['지점번호', '일시', '강수량(mm)', '일최다강수량(mm)', '구역', '연도', '월'], dtype='object')

    지점번호         일시  강수량(mm)  일최다강수량(mm)       구역    연도   월
0    105 2020-01-01    107.5        50.0  강원도(강릉)  2020   1
1    105 2020-02-01     77.5        43.5  강원도(강릉)  2020   2
2    105 2020-03-01     47.1        17.3  강원도(강릉)  2020   3
3    105 2020-04-01     65.6        23.3  강원도(강릉)  2020   4
4    105 2020-05-01     95.5        26.7  강원도(강릉)  2020   5
..   ...        ...      ...         ...      ...   ...  ..
67   105 2025-08-01     41.1        22.7  강원도(강릉)  2025   8
68   105 2025-09-01    339.8       103.7  강원도(강릉)  2025   9
69   105 2025-10-01    486.2        77.5  강원도(강릉)  2025  10
70   105 2025-11-01     17.3        11.6  강원도(강릉)  2025  11
71   105 2025-12-01      6.6         6.2  강원도(강릉)  2025  12

[72 rows x 7 columns]